config/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views


movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    # redirect 'movies/' to movies/urls.py
    path('movies/', include('movies.urls')),
    # 'model_resource.urls' returns URLs based on 'resource_name'
    path('api/', include(movie_resource.urls))
]

movies/urls.py
from django.urls import path
from . import views # . is curr dir

# URLs starting with 'movies/'

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    # <> is to pass a parameter
    path('<int:movie_id>', views.detail, name='detail')
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        # queryset is query executed later (lazy loading, lazy object)
        queryset = Movie.objects.all()
        resource_name = 'movies' # after .../api/ URL
        excludes = ['date_created']

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here(Model is a table in DB).
class Genre(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self): # change name of Genres in Admin panel
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now) # pass reference to timezone.now() func

api/views.py
from django.shortcuts import render

# Create your views here.

config/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.
def index(request):
    # SELECT * FROM movies_movie ↓
    movies = Movie.objects.all()

    # # SELECT * FROM movies_movie WHERE ↓
    # Movie.objects.filter(release_year=1985)
    # # SELECT * FROM movies_movie WHERE(single object) ↓
    # Movie.objects.get(id=1)
    
    # passing 'movies' object to index.html with {'movies': movies}
    return render(request, 'movies/index.html', {'movies': movies})

def detail(request, movie_id):
    # pk is primary key(id)
    movie = get_object_or_404(Movie, pk=movie_id)
    # passing 'movie' object to detail.html with {'movie': movie}
    return render(request, 'movies/detail.html', {'movie': movie})

movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
    <dl> <!--description list-->
        <dt>Title</dt> <!--description term-->
        <dd>{{ movie.title }}</dd> <!--description description-->
        <dt>Genre</dt> <!--description term-->
        <dd>{{ movie.genre }}</dd> <!--description description-->
        <dt>Stock</dt> <!--description term-->
        <dd>{{ movie.number_in_stock }}</dd> <!--description description-->
    </dl>
{% endblock  %}

movies/templates/movies/index.html
{% extends "base.html" %}
{% block content %}
    <!-- zen-code: table.table>thead>tr>th*3 -->
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for m in movies %}
            <tr>
                <td>
                    <a href="{% url 'movies:detail' m.id %}">{{ m.title }}</a>
                </td>
                <td>{{ m.genre }}</td>
                <td>{{ m.number_in_stock }}</td>
                <td>{{ m.daily_rate }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Filmio</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Filmio</a>
    </nav>
    <main class='container'>
        {% block content %}
        {% endblock  %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock  %}